title: 动漫
cid: anime
order: 1
collections:
  - title: NyaFun动漫
    link: https://www.nyadm.net/
    description: ""
    proxy: false
  - title: 片库2号机
    link: https://www.pkmp4.com/
    description: ""
    proxy: true
  - title: agemys 动漫
    link: https://www.agemys.cc/
    description: ""
    proxy: true
  - title: 番组放送
    link: https://bgmlist.com/
    description: 动漫信息
    proxy: true
  - title: 動畫線上看
    link: https://www.anime1.me/
    description: ""
    proxy: false
  - title: Bangumi 番组计划
    link: https://bgm.tv/
    description: 专注于动漫、音乐、游戏领域，帮助你分享、发现与结识同好的ACG网络
    proxy: false
  - title: 动漫 蜜柑计划
    link: https://mikanani.me/
    description: ""
    proxy: true
  - title: 诸神字幕组
    link: https://sub.kamigami.org/
    description: 诸神字幕组 - 诸神字幕组官方发布站..
    proxy: true
  - title: 动漫花园
    link: https://share.dmhy.org/
    description: 動漫花園資訊網是一個動漫愛好者交流的平台,提供最及時,最全面的動畫,漫畫,動漫音樂,動漫下載,BT,ED,動漫遊戲,資訊,分享,交流,讨论.
    proxy: true
  - title: 旋风动漫
    link: http://share.xfapi.top:88/
    description: 旋风动漫BT站为漫迷提供日本动画，漫画，片源，动漫音乐，动漫游戏等资源下载。动漫资源，尽在旋风动漫BT下载频道。
    proxy: false
