// Code generated by goctl. DO NOT EDIT.
// goctl 1.7.3

package types

type AnyRequest struct {
}

type Collection struct {
	ID          string   `json:"id"`
	Title       string   `json:"title"`
	Category    string   `json:"category"`
	Link        string   `json:"link"`
	Description string   `json:"description"`
	Country     string   `json:"country"`
	Thumbnail   string   `json:"thumbnail"`
	Tags        []string `json:"tags" gorm:"type:json"`
	View        int      `json:"view"`
}

type CollectionRequest struct {
	ID          string   `json:"id"`
	Title       string   `json:"title"`
	Category    string   `json:"category"`
	Link        string   `json:"link"`
	Description string   `json:"description"`
	Country     string   `json:"country"`
	Thumbnail   string   `json:"thumbnail"`
	Tags        []string `json:"tags"`
}

type CollectionsResponse struct {
	Collections []Collection `json:"collections"`
}

type Comment struct {
	ID           string `json:"id"`
	CollectionId string `json:"collection_id"`
	Nickname     string `json:"nickname"`
	Message      string `json:"message"`
}

type CommentRequest struct {
	CollectionId string `json:"collection_id"`
	Nickname     string `json:"nickname"`
	Message      string `json:"message"`
}

type CommentsResponse struct {
	Comments []Comment `json:"comments"`
}

type IDRequest struct {
	ID int `json:"string"`
}

type IDResponse struct {
	ID int `json:"string"`
}

type TagRequest struct {
	Tags []string `json:"tags"`
}

type TagsResponse struct {
	Tags []string `json:"tags"`
}
