# https://taskfile.dev

version: "3"

vars:
  GREETING: Hello, World!

tasks:
  api rebuild:
    cmds:
      - powershell -Command "if (Test-Path 'backend\\internal\\types\\types.go') { Remove-Item 'backend\\internal\\types\\types.go' -Recurse -Force }"
      - goctl api go --api ./backend/api/main.api --dir backend
  api doc:
    cmds:
      - powershell -Command "Remove-Item 'backend\\doc' -Recurse -Force -ErrorAction SilentlyContinue"
      - goctl api doc --dir ./backend/api --o ./backend/doc
      - powershell -Command "Remove-Item 'backend\\doc\\main.md' -Force"
