title: 漫画
cid: comic
order: 3
collections:
  - title: 动漫之家
    link: https://manhua.dmzj.com/
    description: 动漫之家漫画网提供海量漫画,全天更新在线漫画欣赏,详尽的动漫资料库、动画资讯、用户评论社区于一体,它与在线动画站、动漫之家宅新闻三站合一，将成为国内更新较快,动漫视听享受较全,资料库较详尽的社区型动漫爱好者的交流互动平台
  - title: 日本漫畫
    link: http://www.mangabz.com/
    description: mangabz是全網資源最全的在線漫畫、日本漫畫閱讀平臺。擁有時下最熱門的日漫作品：鬼滅之刃、一拳超人213、海賊王1053、火影忍者、死神等。超快的更新速度，第一時間為你奉上極致的閱讀體驗。
    tags: [代理]
