title: 网校
cid: school
order: 5
collections:
  - title: School of Motion
    link: https://www.schoolofmotion.com/
    description: Hone your Motion Design skills and career with interactive online courses, a welcoming community, and critique from industry pros.
    proxy: false
  - title: Motioner 二棲知學
    link: https://motioner.tw/
    description: Motioner 提供最專業的動態設計領域線上課程，透過多元領域、深入淺出的課程規劃與專欄文章，帶你找到最適合自己的設計學習資源，讓你設計學習路上不孤單！·
    proxy: false
  - title: Motion Design School
    link: https://motiondesign.school/
    description: ""
    proxy: false
