Name: main
Host: 0.0.0.0
Port: 8888

Resource:
  Announces: resource\\announces
  Collections: resource\\collections
  Icons: resource\\icons
  Comments: resource\\comments
  MetaFile: meta.yaml

Database:
  Resource: resource\\database\\core.db

System:
  Username: admin
  Password: admin
  JwtSecret: yuelilili # 需要8字符以上
