title: 工具
cid: tool
order: 7
collections:
  - cid: www.mojidict.com
    title: MOJI辞书
    link: https://www.mojidict.com/
    description: 学日语的
    country: ""
    proxy: false
    thumbnail: http://nav.yuelili.com/wp-content/uploads/82cf7-www.mojidict.com.png
    view: 0
  - cid: www.lexilogos.com
    title: 在线输入各国语言
    link: https://www.lexilogos.com/keyboard/japanese.php
    description: ""
    country: ""
    proxy: false
    thumbnail: http://nav.yuelili.com/wp-content/uploads/c3082-www.lexilogos.com.png
    view: 0
  - cid: dictionary.cambridge.org
    title: 剑桥词典
    link: https://dictionary.cambridge.org/
    description: The most popular dictionary and thesaurus for learners of English. Meanings and definitions of words with pronunciations and translations.
    country: 新加坡
    proxy: false
    thumbnail: https://nav.yuelili.com/wp-content/uploads/e116a-dictionary.cambridge.org.png
    view: 0
  - cid: www.oxfordlearnersdictionaries.com
    title: 牛津词典
    link: https://www.oxfordlearnersdictionaries.com/
    description: The largest and most trusted free online dictionary for learners of British and American English with definitions, pictures, example sentences, synonyms, antonyms, word origins, audio pronunciation, and more. Look up the meanings of words, abbreviations, phrases, and idioms in our free English Dictionary.
    country: 新加坡
    proxy: false
    thumbnail: https://nav.yuelili.com/wp-content/uploads/477e3-www.oxfordlearnersdictionaries.com.png
    view: 0
  - cid: soundoftext.com
    title: 文字转语音
    link: https://soundoftext.com/
    description: ""
    country: ""
    proxy: false
    thumbnail: https://nav.yuelili.com/wp-content/uploads/a496f-soundoftext.com.png
    view: 0
