title: 电影
cid: movie
order: 2
collections:
  - title: 电影狗
    link: https://www.dianyinggou.com/
    description: ""
    proxy: false
  - title: BT电影下载
    link: https://www.kuba222.com/
    description: 酷吧电影下载网
    proxy: false
  - title: 美剧迷
    link: https://www.meijumi.net/
    description: ""
    proxy: false
  - title: dianying.fm电影资源整合
    link: https://dianying.fm/
    description: dianying.fm
    proxy: false
