title: 官网
cid: official
order: 1
collections:
  - title: TED
    link: https://www.ted.com/
    description: TED Talks are influential videos from expert speakers on education, business, science, tech and creativity, with subtitles in 100+ languages. Ideas free to stream and download.
    proxy: false
    thumbnail: https://nav.yuelili.com/wp-content/uploads/97703-www.ted.com.png
    view: 0
