// Code generated by goctl. DO NOT EDIT.
// goctl 1.7.3

export interface AnyRequest {}

export interface Category {
  iD: number
  createdAt: string
  updatedAt: string
  cid?: string
  depth?: number
  title: string
  order?: number
  path?: string
}

export interface Collection {
  iD: number
  createdAt: string
  updatedAt: string
  cid: string
  proxy?: boolean
  title: string
  link: string
  path?: string
  categoryID: string // 外键字段
  category: Category
  description?: string
  country?: string
  thumbnail?: string
  tags?: Array<string>
  view?: number
}

export interface CollectionsData {
  category: Category // 使用 inline 标签将 Category 字段内联
  groups: Array<Group>
}

export interface CollectionsResponse {
  datas: Array<CollectionsData>
}

export interface Comment {
  id: string
  collection_id: string
  nickname: string
  message: string
}

export interface Record {
  iD: number
  createdAt: string
  updatedAt: string
}

export interface CommentRequest {
  collection_id: string
  nickname: string
  message: string
}

export interface CommentsResponse {
  comments: Array<Comment>
}

export interface Group {
  category: Category // 使用 inline 标签将 Category 字段内联
  collections: Array<Collection>
  show: boolean
}

export interface IDRequest {
  id: number
}

export interface IDResponse {
  id: number
}

export interface Model {
  iD: number
  createdAt: string
  updatedAt: string
}

export interface TagRequest {
  tags: Array<string>
}

export interface TagsResponse {
  tags: Array<string>
}
