title: 模型
cid: model
order: 7
collections:
  - title: TurboSquid
    link: https://www.turbosquid.com/
    description: Buy 3D models for your project from our vast online catalog of cars, people, textures, architectural models and more.
  - title: Sketchfab
    link: https://sketchfab.com/feed
    description: 我们拥有超过一百万创作者的社区，是全球最大的在网络、移动设备、AR 和 VR 上发布、共享和发现 3D 内容的平台。
  - title: Free 3D
    link: https://free3d.com/
    description: Just a moment...
  - title: Mixamo动画库
    link: https://www.mixamo.com/#/
    description: Mixamo
