title: 官网
cid: official
order: 1
collections:
  - cid: www.unrealengine.com
    title: Unreal
    link: https://www.unrealengine.com/
    description: Unreal Engine is the world’s most open and advanced real-time 3D creation tool for photoreal visuals and immersive experiences.
    proxy: false
    thumbnail: https://nav.yuelili.com/wp-content/uploads/b4aa0-www.unrealengine.com.png
    view: 0
  - cid: www.foundry.com
    title: Nuke
    link: https://www.foundry.com/
    description: Foundry creates pioneering software for creative industries across Digital Design, Media and Entertainment.
    proxy: false
    thumbnail: https://nav.yuelili.com/wp-content/uploads/af2c1-www.foundry.com.png
    view: 0
  - cid: www.smithmicro.com
    title: Smith Micro
    link: https://www.smithmicro.com/
    description: Proven Solutions For Wireless Service Providers To Enrich Today&#039;s Connected Lifestyles And Engage Consumers Via Smartphones And Consumer IoT
    proxy: false
    thumbnail: https://nav.yuelili.com/wp-content/uploads/96bd3-www.smithmicro.com.png
    view: 0
  - cid: www.autodesk.com
    title: Autodesk
    link: https://www.autodesk.com/
    description: Autodesk is a global leader in design and make technology, with expertise across architecture, engineering, construction, design, manufacturing, and entertainment.
    proxy: false
    thumbnail: https://nav.yuelili.com/wp-content/uploads/89eae-www.autodesk.com.png
    view: 0
  - cid: www.maxon.net
    title: Maxon
    link: https://www.maxon.net
    description: Maxon tools include the award-winning Cinema 4D suite of 3D modeling, simulation and animation technology, the Red Giant lineup of revolutionary editing,…
    proxy: false
    thumbnail: https://nav.yuelili.com/wp-content/uploads/250b2-www.maxon.net.png
    view: 0
  - cid: substance3d.adobe.com
    title: Substance
    link: https://substance3d.adobe.com/community-assets/
    description: ""
    proxy: false
    thumbnail: https://nav.yuelili.com/wp-content/uploads/7c93c-substance3d.adobe.com.png
    view: 0
  - cid: pixologic.com
    title: ZBrush
    link: http://pixologic.com/
    description: Find ZBrush Retailers, and stores that offer product sales, pricing and purchase.
    proxy: false
    thumbnail: https://nav.yuelili.com/wp-content/uploads/30793-pixologic.com.png
    view: 0
