title: 格式
cid: convert
order: 2
collections:
  - title: File Converter
    link: https://convertio.co/zh/
    description: Convertio - Easy tool to convert files online. More than 309 different document, image, spreadsheet, ebook, archive, presentation, audio and video formats supported.
    proxy: false
  - title: 图片无损放大
    link: https://bigjpg.com/
    description: ""
    proxy: false
  - title: TinyPNG
    link: https://tinypng.com/
    description: TinyPNG – 图片在线压缩
    proxy: false
  - title: 音乐解锁
    link: https://demo.unlock-music.dev/
    description: 音频解密
    proxy: false
  - title: Remove Background from Image
    link: https://www.remove.bg/zh
    description: 移除图片背景
    proxy: false
  - title: 人声伴奏分离
    link: https://vocalremover.org/
    description: Just a moment...
    proxy: false
  - title: 翻译文档
    link: https://www.onlinedoctranslator.com/zh-CN/
    description: "Free, Online Document Translator which translates office documents (PDF, Word, Excel, PowerPoint, OpenOffice, text) into multiple languages, preserving the original layout. Supported file formats: Word: doc, docx; PDF: pdf; Excel: xls, xlsx; Powerpoint; ppt, pptx; Text xml, txt.... This translator supports: English, Afrikaans, Albanian, Arabic, Armenian, Azerbaijani, Basque, Belarusian, Bulgarian, Catalan, Chinese, Croatian, Czech, Danish, Dutch, Estonian, Filipino, Finnish, French, Galician, Georgian, German, Greek, Haitian Creole, Hebrew, Hindi, Hungarian, Icelandic, Indonesian, Irish, Italian, Japanese, Korean, Latvian, Lithuanian, Macedonian, Malay, Maltese, Norwegian, Persian, Polish, Portuguese, Romanian, Russian, Serbian, Slovak, Slovenian, Spanish, Swahili, Swedish, Thai, Turkish, Ukrainian, Urdu, Vietnamese, Welsh, Yiddish"
    proxy: false
