title: 软件
cid: tool
order: 1
collections:
  - cid: www.processon.com
    title: ProcessOn
    link: https://www.processon.com/
    description: 在线思维导图、组织结构图、网络拓扑图、BPMN、UML图、UI界面原型设计、iOS界面原型设计等。同时依托于互联网实现了人与人之间的实时协作和共享。
    proxy: false
    thumbnail: http://nav.yuelili.com/wp-content/uploads/96647-www.processon.com.png
    view: 0
  - cid: www.billfish.cn
    title: Billfish 素材管理工具
    link: https://www.billfish.cn/
    description: Billfish是专为设计师打造的素材管理工具，可以高效的整理电脑的各类素材：支持PNG、JPG、PSD、AI、GIF、SVG、EPS、CDR等格式。Billfish素材管理工具可以快速、轻松的管理素材，让你拥有更多的时间专注于设计本身。
    proxy: false
    thumbnail: https://nav.yuelili.com/wp-content/uploads/cf584-www.billfish.cn.png
    view: 0
  - cid: petalica.com
    title: AI线稿上色
    link: https://petalica.com/index_zh.html
    description: Petalica Paint
    proxy: false
    thumbnail: https://nav.yuelili.com/wp-content/uploads/6b6ef-petalica.com.png
    view: 0
  - cid: www.autopiano.cn
    title: 自由钢琴
    link: https://www.autopiano.cn/
    description: 在线弹钢琴
    proxy: false
    thumbnail: http://nav.yuelili.com/wp-content/uploads/7bb45-www.autopiano.cn.png
    view: 0
  - cid: trace.moe
    title: 动漫场景识别检测 | 查找时间点
    link: https://trace.moe/
    description: Search Anime by ScreenShot. Lookup the exact moment and the episode.
    proxy: false
    thumbnail: https://nav.yuelili.com/wp-content/uploads/d5832-trace.moe.png
    view: 0
  - cid: docsmall.com
    title: docsmall
    link: https://docsmall.com/
    description: docsmall提供在线图片压缩、GIF压缩、在线PDF压缩、PDF合并、PDF分割功能
    proxy: false
    thumbnail: http://nav.yuelili.com/wp-content/uploads/5d7de-docsmall.com.png
    view: 0
  - cid: www.latexlive.com
    title: 在线LaTeX公式编辑器
    link: https://www.latexlive.com/
    description: 识别图片中的公式！免费的在线LaTeX公式编辑器。支持导出svg、超大png、jpg、MathML、SVGCode。可以打出任何公式，不只是数学！支持物理physics、化学mhchem、unicode等常用扩展宏包加载。即时渲染，基于MathJax实现。
    proxy: false
    thumbnail: https://nav.yuelili.com/wp-content/uploads/245ec-www.latexlive.com.png
    view: 0
  - cid: www.geogebra.org
    title: GeoGebra 在线绘图
    link: https://www.geogebra.org/calculator
    description: GeoGebra - the world’s favorite, free math tools used by over 100 million students and teachers
    proxy: false
    thumbnail: https://nav.yuelili.com/wp-content/uploads/ac4d7-www.geogebra.org.png
    view: 0
  - cid: www.codecogs.com
    title: 在线Latex
    link: https://www.codecogs.com/latex/eqneditor.php?lang=zh-cn
    description: Interactive Open Source Numerical Library of C/C++ functions for Engineering, Finance, Maths, Science and Statistics. With Online Calculators for Numerical Components and Excel Add-ins.
    proxy: false
    thumbnail: https://nav.yuelili.com/wp-content/uploads/a1171-www.codecogs.com.png
    view: 0
  - cid: ascii2d.net
    title: 二次元画像詳細
    link: https://ascii2d.net/
    description: 2D 图像详细搜索
    proxy: false
    thumbnail: ""
    view: 0
  - cid: nav.yuelili.com
    title: 免费手绘人物
    link: https://nav.yuelili.com/sites/free-hand-drawn-characters.html
    description: "类似的网站还有: https://www..."
    proxy: false
    thumbnail: https://nav.yuelili.com/wp-content/uploads/d4ffb-www.openpeeps.com.png
    view: 0
  - cid: x.magiconch.com
    title: 梗图生成器
    link: https://x.magiconch.com/
    description: 梗图生成器 - 神奇海螺
    proxy: false
    thumbnail: https://nav.yuelili.com/wp-content/uploads/6f799-x.magiconch.com.png
    view: 0
  - cid: www.yciyun.com
    title: 词云生成
    link: https://www.yciyun.com/
    description: 最简单的在线生成中文字云的网站，易词云是一款优秀的在线中文词云生成网站，具有分词功能，内含多种形状模板，不同的配色方案，可供选择
    proxy: false
    thumbnail: https://nav.yuelili.com/wp-content/uploads/b715d-www.yciyun.com.png
    view: 0
  - cid: temporarymail.com
    title: 临时邮箱
    link: https://temporarymail.com/
    description: Create disposable and temporary email addresses in an instant without the hassle of receiving spam or needing to sign up.
    proxy: false
    thumbnail: https://nav.yuelili.com/wp-content/uploads/3993b-temporarymail.com.png
    view: 0
  - cid: www.p2hp.com
    title: 在线录屏
    link: https://www.p2hp.com/screenrecord.html
    description: ""
    proxy: false
    thumbnail: https://nav.yuelili.com/wp-content/uploads/79734-www.p2hp.com.png
    view: 0
