title: 官网
cid: official
order: 1
collections:
  - title: Python
    link: https://www.python.org/
    description: The official home of the Python Programming Language
    proxy: false
  - title: Go Language
    link: https://go.dev/
    description: Go is an open source programming language that makes it easy to build simple, reliable, and efficient software.
    proxy: false
