title: 其他
cid: other
order: 8
collections:
  - cid: www.science.org
    title: Science
    link: https://www.science.org/
    description: Science | AAAS
    proxy: false
    thumbnail: https://nav.yuelili.com/wp-content/uploads/72a77-www.science.org.png
    view: 0
