title: 资源
cid: resource
order: 3
collections:
  - title: LookAE.com
    link: https://www.lookae.com/
    description: LookAE.com 是大众脸为您提供的CG后期技术交流平台，欢迎您的到来。
    proxy: false
  - title: C4DSKY
    link: https://c4dsky.com/
    description: AK Element 3d Videocopilot ,AEP ​cinema 4d AE C4D R20 教程 插件 中文字幕教程 汉化插件CG教程 CG素材-C4DSKY-书生-fcpx videohive 免费AE模板 Realflow
    proxy: false
  - title: 龋齿一号GFXCamp
    link: https://www.gfxcamp.com/
    description: 最新最热CG资源分享,龋齿一号GFXCamp,CG营地,视频素材,AE模板,CG教程,插件,软件
    proxy: false
  - title: flashback
    link: https://flashbackj.com/
    description: 外国正版插件/PDF购买网站
    proxy: false
  - title: aescripts
    link: https://aescripts.com/
    description: Just a moment...
    proxy: false
  - title: BOOTH
    link: https://booth.pm/zh-cn
    description: 外国正版软件/脚本/模型购买
    proxy: false
