title: 资源
cid: resource
order: 3
collections:
  - title: 在线生成MD表格
    link: http://web.chacuo.net/charsettextmarkdown
    description: ""
    proxy: false
    thumbnail: http://nav.yuelili.com/wp-content/uploads/27aef-web.chacuo.net.png
    view: 0
  - title: 代码片段生成器
    link: https://snippet-generator.app/
    description: 哈哈哈 懒癌必备
    proxy: false
    thumbnail: https://nav.yuelili.com/wp-content/uploads/b7a20-snippet-generator.app.png
    view: 0
  - title: codepen 在线写html
    link: https://codepen.io/
    description: Attention Required! | Cloudflare
    proxy: false
    thumbnail: https://nav.yuelili.com/wp-content/uploads/d292a-codepen.io.png
    view: 0
  - title: CSS格式化
    link: http://www.lonniebest.com/FormatCSS/
    description: This is, quite possibly, the best computer automated card trick on the Internet.
    proxy: false
    thumbnail: https://nav.yuelili.com/wp-content/uploads/82339-www.lonniebest.com.png
    view: 0
  - title: 在线编程 | 多语言
    link: https://rextester.com/l/octave_online_compiler
    description: compile c# online
    proxy: false
    thumbnail: ""
    view: 0
  - title: 在线编程2 | 多语言
    link: https://www.onlinegdb.com/
    description: Online GDB is online compiler and debugger for C/C++. You can compile, run and debug code with gdb online. Using gcc/g++ as compiler and gdb as debugger. Currently C and C++ languages are supported.
    proxy: false
    thumbnail: https://nav.yuelili.com/wp-content/uploads/b2686-www.onlinegdb.com.png
    view: 0
  - title: regex101 正则
    link: https://regex101.com/
    description: ""
    proxy: false
    thumbnail: https://nav.yuelili.com/wp-content/uploads/35692-regex101.com.png
    view: 0
  - title: Overleaf | Latex
    link: https://www.overleaf.com/
    description: An online LaTeX editor that’s easy to use. No installation, real-time collaboration, version control, hundreds of LaTeX templates, and more.
    proxy: false
    thumbnail: https://nav.yuelili.com/wp-content/uploads/8f9f5-www.overleaf.com.png
    view: 0
  - title: 力扣
    link: https://leetcode.cn/
    description: 力扣
    proxy: false
    thumbnail: https://nav.yuelili.com/wp-content/uploads/3ddc4-leetcode.cn.png
    view: 0
  - title: AtCoder
    link: https://atcoder.jp/
    description: AtCoder is a programming contest site for anyone from beginners to experts. We hold weekly programming contests online.
    proxy: false
    thumbnail: https://nav.yuelili.com/wp-content/uploads/5c9c9-atcoder.jp.png
    view: 0
  - title: Codeforces
    link: http://codeforces.com/
    description: Codeforces. Programming competitions and contests, programming community
    proxy: false
    thumbnail: https://nav.yuelili.com/wp-content/uploads/2ad20-codeforces.com.png
    view: 0
